<?php
require_once 'connect.php';
require_once 'functions.php';
require_once 'product.php';


?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="style.css">
</head>

<style>


</style>

<body>
<a class='button' href="/db/pdo/create.phtml">Add product</a>
<div class="container">
  <table>
    <thead>
      <tr>
        <th scope="col">productCode</th>
        <th scope="col">productName</th>
        <th scope="col">productLine</th>
        <th scope="col">productScale</th>
        <th scope="col">productVendor</th>
        <th scope="col">productDescription</th>
        <th scope="col">quantityInStock</th>
        <th scope="col">buyPrice</th>
        <th scope="col">MSRP</th>
        <th scope="col">action</th>
      </tr>
    </thead>

    <tbody class="table">


      <?php
      foreach ($products as $product) {
        ?>
        <tr class="tbtr">
          <th scope="row">
            <?= $product['productCode'] ?>
          </th>
          <td>
            <?= $product['productName'] ?>
          </td>
          <td>
            <?= $product['productLine'] ?>
          </td>
          <td>
            <?= $product['productScale'] ?>
          </td>
          <td>
            <?= $product['productVendor'] ?>
          </td>
          <td>
            <?= $product['productDescription'] ?>
          </td>
          <td>
            <?= $product['quantityInStock'] ?>
          </td>
          <td>
            <?= $product['buyPrice'] ?>
          </td>
          <td>
            <?= $product['MSRP'] ?>
          </td>

          <td><a class='button' href="/db/pdo/edit.phtml?id_update=<?= $product['productCode'] ?>">update</a></td>
          <td><a class='button' href="/db/pdo/index.phtml?id_delete=<?= $product['productCode'] ?>">delete</a></td>
        </tr>
      <?php } ?>
    </tbody>
  </table>
  </div>
  <a class='button' href="/db/pdo/create.phtml">Add product</a>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
</body>

</html>