<?php
$dataDog = file_get_contents('https://dog.ceo/api/breeds/image/random');
$dataCat = file_get_contents('https://api.thecatapi.com/v1/images/search?limit=10');
$dog = json_decode($dataDog, true);
$cat = json_decode($dataCat, true)
    ?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<style>
        .img-box {
                overflow: hidden;
            }
            .img-box img {
                width: 600px; 
                height: 600px; 
                transition: transform 0.3s ease; 
            }
            .img-box:hover img {
                transform: scale(1.1); 
            }
        </style>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
            <div class="img-box">
                <img src="<?= $dog['message'] ?>" alt="">
            </div>
            </div>
            <div class="col-md-6">
            <div class="img-box">
                <img src="<?= $cat[1]['url'] ?>" alt="">
            </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>
